djangodenmark/apps/accounts/urls.py
from django.urls import path

from .views import SignUpView


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

djangodenmark/apps/events/urls.py
from django.urls import path

from .views import AboutView
from .views import IndexView


app_name = "events"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
]

djangodenmark/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django_consent import urls as consent_urls

from .apps.companies import urls as company_urls
from .apps.events import urls as event_urls
from .apps.jobposts import urls as jobpost_urls
from .apps.newsletter import urls as newsletter_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(event_urls)),
    path("accounts/", include("djangodenmark.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("companies/", include(company_urls)),
    path("jobs/", include(jobpost_urls)),
    path("consent/", include(consent_urls)),
    path("newsletter/", include(newsletter_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # conditionally adding django-debug-toolbar URLs
    # make sure to include in INSTALLED_APPS + MIDDLEWARE + INTERNAL_IPS are set
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

meetup/urls.py
from django.urls import path

from . import views



app_name = 'meetup'

urlpatterns = [
    path('', views.MeetupEventListView.as_view(),),
]

djangodenmark/apps/companies/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


class Company(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    logo_image = models.ImageField(
        upload_to="images/",
        null=True,
        verbose_name="Company logo",
    )
    company_name = models.CharField(max_length=145, verbose_name="Company name")
    description = models.TextField(verbose_name="Describe your companies")
    website_url = models.URLField(
        max_length=200,
        blank=True,
        validators=[
            RegexValidator(
                regex="[http]",
                message="Website URL must include https:// or http://",
                code="invalid_url",
            ),
        ],
        verbose_name="Link to your website",
    )
    relation_to_django = models.TextField(
        verbose_name="Your relation to Django",
    )
    email = models.EmailField(max_length=100)
    main_contact = models.CharField(
        max_length=100,
        verbose_name="The main point of contact",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.company_name

djangodenmark/apps/events/models.py
from django.db import models

# Create your models here.

# All fields, Event should contain with string conversion


class Event(models.Model):
    event_title = models.CharField(max_length=100)
    date = models.DateField()
    location = models.CharField(max_length=145)
    description = models.TextField()
    event_url = models.CharField(max_length=100)
    event_image = models.ImageField(upload_to="images/events/", null=True)

    def __str__(self):
        return "{} {} {} {} {}".format(
            self.event_title, self.date, self.location, self.description, self.event_url
        )

djangodenmark/apps/jobposts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Available titles for searching jobs
JOBTYPE_CHOICES = (
    ("PartTime", "Part-time"),
    ("FullTime", "Full-time"),
    ("Freelancer", "Freelancer"),
    ("Internship", "Internship"),
    ("Other", "Other"),
)


class Jobpost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job_title = models.CharField(max_length=60, verbose_name="Job title")
    job_company_name = models.CharField(max_length=100, verbose_name="Company name")
    job_description = models.TextField(verbose_name="Describe the position")
    job_type = models.CharField(
        max_length=11, choices=JOBTYPE_CHOICES, verbose_name="Job type"
    )
    job_location = models.CharField(max_length=100, verbose_name="Location")
    job_contact_person = models.CharField(max_length=80, verbose_name="Contact person")
    job_apply_url = models.URLField(
        max_length=200,
        blank=True,
        verbose_name="Link to job application",
    )

    def __str__(self):
        return f"{self.job_title} at {self.job_company_name}"

    def get_update_url(self):
        """return URL for update view - for use in templates
        since JS is being used on frontend, making this a model method is easier
        than using url template tag to avoid showing unnecessary errors in code editors
        """
        return reverse("jobpost_update", args=[self.pk])

djangodenmark/apps/companies/forms.py
from django.forms import ModelForm

from .models import Company


class CompanyForm(ModelForm):
    class Meta:
        model = Company
        exclude = ("user", "created_at")
        fields = "__all__"

djangodenmark/apps/jobposts/forms.py
from django.forms import ModelForm

from .models import Jobpost


class JobpostForm(ModelForm):
    """Form for users to add Jobpost from front end"""

    class Meta:
        model = Jobpost
        exclude = ("user",)
        fields = "__all__"

djangodenmark/apps/memberships/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import forms as auth_forms
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _


class InviteForm(forms.Form):
    invite_code = forms.CharField(
        label=_("Invite code"),
    )

    def clean_invite_code(self):
        invite_code = self.cleaned_data.get("invite_code", None) or ""
        invite_code = invite_code.lower()
        if invite_code not in settings.DJANGO_DENMARK_INVITE_CODES:
            raise forms.ValidationError(gettext("Invite code isn't valid"))
        return invite_code


class SignupForm(auth_forms.UserCreationForm):
    class Meta(auth_forms.UserCreationForm.Meta):
        fields = ("username", "email")

djangodenmark/apps/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

djangodenmark/apps/companies/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import CompanyForm
from .models import Company
from djangodenmark.apps.jobposts.models import Jobpost


# CreateView
class CompanyFormView(LoginRequiredMixin, CreateView):
    model = Company
    template_name = "companies/createCompanyProfile.html"
    form_class = CompanyForm
    success_url = "/companies/detailViewEditUpdateProfile"

    # Checks if data input is valid and saves object
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class CompanyView(ListView):
    model = Company
    template_name = "companies/companyoverview.html"


# DetailView
# CompanyDetailViewEditUpdate takes 2 parameters LoginRequiredMixin to secure different
# functionalities for users when signed in or not and ListView.
class CompanyDetailView(DetailView):
    model = Company
    template_name = "companies/detailViewCompanyProfile.html"
    fields = "__all__"


class CompanyDetailViewEditUpdate(LoginRequiredMixin, ListView):
    model = Company
    template_name = "companies/detailViewEditUpdateProfile.html"
    fields = "__all__"

    # get_queryset(self) secures to display Company profiles that the User is creater/owner of.
    def get_queryset(self):
        return (
            super(CompanyDetailViewEditUpdate, self)
            .get_queryset()
            .filter(user=self.request.user)
        )

    # get_context_data(self, **kwargs) makes it possible for two ListViews containing different
    # sets of data to be displayed on the same html page. In this case objects from jobposts.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        my_jobposts = Jobpost.objects.filter(user=self.request.user)
        context["jobpost_list"] = my_jobposts
        return context


# UpdateView
class UpdateCompanyFormView(LoginRequiredMixin, UpdateView):
    model = Company
    template_name = "companies/updateCompanyProfile.html"
    form_class = CompanyForm
    success_url = "/companies/detailViewEditUpdateProfile"


# DeleteView
class DeleteCompanyFormView(DeleteView):
    model = Company
    template_name = "companies/detailViewEditUpdateProfile.html"
    success_url = "/companies/detailViewEditUpdateProfile"

djangodenmark/apps/events/views.py
from django.views.generic import ListView

from .models import Event
from djangodenmark.apps.companies.models import Company


class IndexView(ListView):
    model = Event
    template_name = "events/index.html"
    ordering = ["-date"]

    # Gets all Event objects and returns a sorted list by creation stamp
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        LandingpageCompany = Company.objects.all().order_by(
            "-created_at",
        )[0:3]
        context["company_list"] = LandingpageCompany
        return context


class AboutView(ListView):
    model = Event
    template_name = "events/about.html"
    ordering = ["-date"]

    # Gets all Event objects and returns a sorted list by creation stamp
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        LandingpageCompany = Company.objects.all().order_by(
            "-created_at",
        )[0:3]
        context["company_list"] = LandingpageCompany
        return context

djangodenmark/apps/jobposts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import JobpostForm
from .models import Jobpost


# Create your views here.
class JobpostCreateView(LoginRequiredMixin, CreateView):
    model = Jobpost
    template_name = "jobposts/jobpost_create.html"
    form_class = JobpostForm
    success_url = "/companies/detailViewEditUpdateProfile"

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class JobpostSearchView(ListView):
    model = Jobpost
    template_name = "jobposts/jobpost_search.html"

    # Makes it possible to search for a specific jobposts by filtering through all jobposts objects
    def get_queryset(self):
        query = self.request.GET.get("q")
        if query is None:
            jobpost_list = Jobpost.objects.all()
            return jobpost_list
        else:
            jobpost_list = Jobpost.objects.filter(
                Q(job_title__icontains=query)
                | Q(job_company_name__icontains=query)
                | Q(job_location__icontains=query)
                | Q(job_type__icontains=query)
            )
            return jobpost_list


# class JobpostDetailView(DetailView):
#   model = Jobpost
# there was never any template made for a detail view - commenting out for now
# currently detail is shown via a modal in JobpostSearchView / jobpost_search.html


# UpdateView
class JobpostUpdateView(LoginRequiredMixin, UpdateView):
    model = Jobpost
    template_name = "jobposts/jobpost_update.html"
    form_class = JobpostForm
    success_url = "/companies/detailViewEditUpdateProfile"


# DeleteView
class JobpostDeleteView(DeleteView):
    model = Jobpost
    template_name = "/companies/detailViewEditUpdateProfile.html"
    success_url = "/companies/detailViewEditUpdateProfile"

djangodenmark/apps/memberships/views.py
from django.contrib.auth.views import LoginView as AuthLoginView
from django.http.response import HttpResponseForbidden
from django.shortcuts import redirect
from django.urls.base import reverse
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.edit import FormView
from django_consent.forms import EmailConsentForm
from django_consent.views import ConsentCreateView

from . import forms


class NewsletterSignupView(ConsentCreateView):
    pass


class StartView(TemplateView):

    template_name = "memberships/start.html"

    # Balder is working on this
    def get_context_data_soon(self, **kwargs):
        c = super().get_context_data(**kwargs)
        c["newsletter_form"] = EmailConsentForm(
            consent_source="x"  # TODO: We need a good way to seed consent such as this.
        )
        return c


class InviteView(FormView):

    form_class = forms.InviteForm
    template_name = "memberships/invite.html"

    def form_valid(self, __):
        self.request.session["invited"] = True
        return redirect("memberships:signup")


class SignupView(CreateView):

    form_class = forms.SignupForm
    template_name = "memberships/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if not self.request.session["invited"]:
            return HttpResponseForbidden("You need to be invited")
        return CreateView.dispatch(self, request, *args, **kwargs)

    def get_success_url(self):
        return reverse("memberships:login")


class LoginView(AuthLoginView):

    template_name = "memberships/login.html"

djangodenmark/apps/newsletter/views.py
from django.urls.base import reverse
from django.views.generic.base import RedirectView
from django_consent import models
from django_consent.views import ConsentConfirmationSentView
from django_consent.views import ConsentCreateView


class Index(RedirectView):

    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        source = models.ConsentSource.objects.all().first()
        if not source:
            source = models.ConsentSource.objects.create(
                source_name="Auto-created default newsletter"
            )
        return reverse("newsletter:signup", kwargs={"source_id": source.id})


class ConsentCreateView(ConsentCreateView):
    template_name = "signup.html"

    def get_success_url(self):
        return reverse(
            "newsletter:signup_confirmation",
            kwargs={"source_id": self.consent_source.id},
        )


class ConsentConfirmationSentView(ConsentConfirmationSentView):
    pass

djangodenmark/templates/base-form.html
{% load widget_tweaks %}

  {% csrf_token %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}
{% comment %} all visible fields in form {% endcomment %}
  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
        {% comment %} fields with errors chown in red with error message {% endcomment %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
        {% comment %} fields with out erros stay green {% endcomment %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
      {% comment %} base styling for fields in form {% endcomment %}
        {% render_field field class="form-control" %}
      {% endif %}
    </div>
  {% endfor %}
    <br>

djangodenmark/templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Django Denmark</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSS -- First link is Bootstrap
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.x/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/header_footer.css' %}">
  <link rel="stylesheet" href="{% static 'css/landingpage.css' %}">
  <link rel="stylesheet" href="{% static 'css/company_job.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">

</head>
<body>
  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url "events:index" %}">Django Denmark</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link" href="{% url "companyoverview" %}">Company Profiles</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'events:about' %}">About Us</a>
            </li>
            {% if user.is_authenticated %}
            <a class="nav-link" href="/company/detailViewEditUpdateProfile">My Page</a>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link"> Hi {{ user.username }}!</a>
            </li>
              <a class="nav-link" href="{% url 'logout' %}"><img class="login-logo" src="{% static 'img/login.png' %}"> Log Out</a>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}?next={{request.path}}"><img class="login-logo" src="{% static 'img/login.png' %}"> Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}"> Signup</a>
              </li>
            {% endif %}
        </ul>
        </div>
    </div>
    </nav>

    <div>
      {% block heroContent %}
      {% endblock %}
    </div>

    <div class="container height-container">
      {% block content %}
      {% endblock %}
    </div>

    <footer>
    <div class="container">
        <div class="row">

            <div class="col-md-4">
                Django Denmark<br>
                Blågårdsgade 19, kl.<br>
                2200 Copenhagen N
            </div>
            <div class="col-md-4">
               <strong>Follow us</strong>
               <p>
               LinkedIn: <a href="https://www.linkedin.com/company/django-danmark/" target="_blank">@django-danmark</a><br>
               Twitter: <a href="https://twitter.com/djangodenmark" target="_blank">@djangodenmark</a><br>
               Meetup: <a href="https://www.meetup.com/The-Copenhagen-Django-Meetup-Group/" target="_blank">Django Copenhagen</a>
               </p>
            </div>
            <div class="col-md-4">
                <strong>Connect</strong>
                <p>
                <a href="mailto:info@django-denmark.org">info@django-denmark.org</a><br>
                <a href="github.com/django-denmark/django-denmark.org/" target="_blank">Modify website on Github</a>
                </p>
            </div>
        </div>
    </div>
    </footer>

    <!-- Boostrap JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.x/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
</body>
</html>