djangodenmark/apps/events/urls.py
from django.urls import path

from .views import AboutView
from .views import IndexView


app_name = "events"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("about/", AboutView.as_view(), name="about"),
]

djangodenmark/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django_consent import urls as consent_urls

from .apps.companies import urls as company_urls
from .apps.events import urls as event_urls
from .apps.jobposts import urls as jobpost_urls
from .apps.newsletter import urls as newsletter_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(event_urls)),
    path("accounts/", include("djangodenmark.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("companies/", include(company_urls)),
    path("jobs/", include(jobpost_urls)),
    path("consent/", include(consent_urls)),
    path("newsletter/", include(newsletter_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # conditionally adding django-debug-toolbar URLs
    # make sure to include in INSTALLED_APPS + MIDDLEWARE + INTERNAL_IPS are set
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

meetup/urls.py
from django.urls import path

from . import views



app_name = 'meetup'

urlpatterns = [
    path('', views.MeetupEventListView.as_view(),),
]

company/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


class Company(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    logo_image = models.ImageField(
        upload_to="images/",
        null=True,
        verbose_name="Company logo",
    )
    company_name = models.CharField(max_length=145, verbose_name="Company name")
    description = models.TextField(verbose_name="Describe your company")
    website_url = models.URLField(
        max_length=200,
        blank=True,
        validators=[
            RegexValidator(
                regex="[http]",
                message="Website URL must include https:// or http://",
                code="invalid_url",
            ),
        ],
        verbose_name="Link to your website",
    )
    relation_to_django = models.TextField(
        verbose_name="Your relation to Django",
    )
    email = models.EmailField(max_length=100)
    main_contact = models.CharField(
        max_length=100,
        verbose_name="The main point of contact",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.company_name

djangodenmark/apps/events/models.py
from django.db import models

# Create your models here.

# All fields, Event should contain with string conversion


class Event(models.Model):
    event_title = models.CharField(max_length=100)
    date = models.DateField()
    location = models.CharField(max_length=145)
    description = models.TextField()
    event_url = models.CharField(max_length=100)
    event_image = models.ImageField(upload_to="images/events/", null=True)

    def __str__(self):
        return "{} {} {} {} {}".format(
            self.event_title, self.date, self.location, self.description, self.event_url
        )

djangodenmark/apps/events/views.py
from django.views.generic import ListView

from .models import Event
from djangodenmark.apps.companies.models import Company


class IndexView(ListView):
    model = Event
    template_name = "events/index.html"
    ordering = ["-date"]

    # Gets all Event objects and returns a sorted list by creation stamp
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        LandingpageCompany = Company.objects.all().order_by(
            "-created_at",
        )[0:3]
        context["company_list"] = LandingpageCompany
        return context


class AboutView(ListView):
    model = Event
    template_name = "events/about.html"
    ordering = ["-date"]

    # Gets all Event objects and returns a sorted list by creation stamp
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        LandingpageCompany = Company.objects.all().order_by(
            "-created_at",
        )[0:3]
        context["company_list"] = LandingpageCompany
        return context

event/views.py
from django.views.generic import ListView

from .models import Event
from company.models import Company


class IndexView(ListView):
    model = Event
    template_name = "event/index.html"
    ordering = ["-date"]

    # Gets all Event objects and returns a sorted list by creation stamp
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        LandingpageCompany = Company.objects.all().order_by(
            "-created_at",
        )[0:3]
        context["company_list"] = LandingpageCompany
        return context


class AboutView(ListView):
    model = Event
    template_name = "event/about.html"
    ordering = ["-date"]

    # Gets all Event objects and returns a sorted list by creation stamp
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        LandingpageCompany = Company.objects.all().order_by(
            "-created_at",
        )[0:3]
        context["company_list"] = LandingpageCompany
        return context

djangodenmark/apps/events/templates/events/about.html
{% extends "events/base.html" %}
{% load static %}

{% block content %}

    <div class="row about-django">
        <div class="col-6">
            <h2>About Us</h2>
            <p>
                Django Danmark<br>
                C/O Arbejdsfællesskabet<br>
                Blågårdsgade 19 kl.<br>
                2200 København N
            </p>
            <p>
                CVR/VAT ID: 39311062
            </p>

            <h2>Association (Forening)</h2>
            <p>The board of the association is:</p>
            <ul>
                <li>Emil B. Kjer (chair)</li>
                <li>Benjamin B. Bach (treasurer)</li>
                <li>Víðir Valberg Guðmundsson</li>
            </ul>

        </div>
        <div class="col-6">
            <img class="about-django-img" src="{% static 'img/hero.png' %}">
        </div>
    </div>

{% endblock %}

djangodenmark/apps/events/templates/events/base.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

djangodenmark/apps/events/templates/events/index.html
{% extends "events/base.html" %}
{% load static %}
{% block heroContent %}
    <div class="hero">
        <img class="hero-img" src="{% static 'img/hero.jpeg' %}">
        <img class="logo" src="{% static 'img/logo.png' %}">
    </div>
{% endblock %}
{% block content %}
{% comment %} What is Django Denmark {% endcomment %}
    <div class="row about-django">
        <div class="col-6">
            <h2>What is Django Denmark?</h2>
            <p>Our mission is to host and support education and networking activities in relation to the Open Source project Django.</p>
            <p>We mostly work through events. These are our major events:</p>
            <ul>
                <li>2018: <a href="https://2018.djangoday.dk/">Django Day Copenhagen</a></li>
                <li>2019: <a href="https://2019.djangocon.eu/">DjangoCon Europe</a> + support for <a href="https://twitter.com/dgcopenhagen">Django Girls Copenhagen</a></li>
                <li>2020: <a href="https://2020.djangoday.dk/">Django Day Copenhagen</a></li>
                <li>2021: <a href="https://djangogirls.org/copenhagen/">Django Girls Copenhagen (April 10th)</a></li>
                <li>2021: <a href="https://2021.djangoday.dk/">Django Day Copenhagen (Sept 24th)</a></li>
            </ul>
        </div>
        <div class="col-6">
            <img class="about-django-img" src="{% static 'img/hero.png' %}">
        </div>
    </div>
{% comment %} Events block {% endcomment %}
    <h1>Events</h1>
    <div class="event-container">
    {% for Event in event_list %}
        <div class="row event-row">
            <div class="col-4 event-col"><img src="{{ Event.event_image.url}}" alt="{{ Event.event_title }}"></div>
            <div class="col-4 event-col">
                <h3 class="event-title">{{ Event.event_title }}</h3>
                <div>Date: {{ Event.date }}</div>
                <div>Location: {{ Event.location }}</div>
                <div>Description: {{ Event.description }}</div>
            </div>
            <div class="col-2 event-col"><a href="{{ Event.event_url }}" class="btn btn-event">Buy tickets</a></div>
        </div>
    {% endfor %}
    </div>
{% comment %} Lastest added companies shown as Boptstrap cards {% endcomment %}
    <h1>Lastest added companies...</h1>
    <div class="card-container landingpage">
    {% for Company in company_list %}
    <div class="card company-card">
                <img class="card-img-top company-logo" src="{{ Company.logo_image.url}}" alt="{{ Company.company_name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ Company.company_name }}</h5>
                    <p class="card-text company-description">{{ Company.description }}</p>
                    <button type="button" class="btn btn-django" data-bs-toggle="modal" data-bs-target="#exampleModal{{ Company.pk }}">See company profile</button>
                    <!-- show company modal starts -->
                    <div class="modal fade" id="exampleModal{{ Company.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                        <div class="modal-header">
                            <img class="card-img-top company-logo" src="{{ Company.logo_image.url}}" alt="{{ Company.company_name }}">
                            <h4 class="modal-title" id="exampleModalLabel">{{ Company.company_name }}</h4 >
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <br>
                        <div class="modal-body row">
                            <div class="col-6">
                                <h6>Company Info</h6>
                                <div>{{ Company.email }}</div>
                                <div class="company-url" onclick="window.location.href='{{ Company.website_url }}'">{{ Company.website_url }}</div>
                            </div>
                            <div class="col-6">
                                <h5>Description:</h5>
                                <p>{{ Company.description }}</p>
                                <h5>Relation to Django:</h5>
                                <p>{{ Company.relation_to_django }}</p>
                            </div>
                        </div>
                        </div>
                        {% comment %} modal ends {% endcomment %}
                    </div>
                    </div>
                </div>
        </div>
        {% endfor %}
        </div>
        </div>
    </div>
{% endblock %}