djangodenmark/apps/companies/urls.py
from django.urls import path

from .views import CompanyDetailView
from .views import CompanyDetailViewEditUpdate
from .views import CompanyFormView
from .views import CompanyView
from .views import DeleteCompanyFormView
from .views import UpdateCompanyFormView

urlpatterns = [
    path("", CompanyView.as_view(), name="companyoverview"),
    path(
        "createCompanyProfile/", CompanyFormView.as_view(), name="createCompanyProfile"
    ),
    path("<pk>/updateCompanyProfile", UpdateCompanyFormView.as_view()),
    path(
        "<pk>/deleteCompanyProfile",
        DeleteCompanyFormView.as_view(),
        name="delete_company",
    ),
    path("<pk>/detailViewCompanyProfile", CompanyDetailView.as_view()),
    path("detailViewEditUpdateProfile/", CompanyDetailViewEditUpdate.as_view()),
]

djangodenmark/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django_consent import urls as consent_urls

from .apps.companies import urls as company_urls
from .apps.events import urls as event_urls
from .apps.jobposts import urls as jobpost_urls
from .apps.newsletter import urls as newsletter_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(event_urls)),
    path("accounts/", include("djangodenmark.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("companies/", include(company_urls)),
    path("jobs/", include(jobpost_urls)),
    path("consent/", include(consent_urls)),
    path("newsletter/", include(newsletter_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # conditionally adding django-debug-toolbar URLs
    # make sure to include in INSTALLED_APPS + MIDDLEWARE + INTERNAL_IPS are set
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

meetup/urls.py
from django.urls import path

from . import views



app_name = 'meetup'

urlpatterns = [
    path('', views.MeetupEventListView.as_view(),),
]

company/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


class Company(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    logo_image = models.ImageField(
        upload_to="images/",
        null=True,
        verbose_name="Company logo",
    )
    company_name = models.CharField(max_length=145, verbose_name="Company name")
    description = models.TextField(verbose_name="Describe your company")
    website_url = models.URLField(
        max_length=200,
        blank=True,
        validators=[
            RegexValidator(
                regex="[http]",
                message="Website URL must include https:// or http://",
                code="invalid_url",
            ),
        ],
        verbose_name="Link to your website",
    )
    relation_to_django = models.TextField(
        verbose_name="Your relation to Django",
    )
    email = models.EmailField(max_length=100)
    main_contact = models.CharField(
        max_length=100,
        verbose_name="The main point of contact",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.company_name

djangodenmark/apps/companies/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models


class Company(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    logo_image = models.ImageField(
        upload_to="images/",
        null=True,
        verbose_name="Company logo",
    )
    company_name = models.CharField(max_length=145, verbose_name="Company name")
    description = models.TextField(verbose_name="Describe your companies")
    website_url = models.URLField(
        max_length=200,
        blank=True,
        validators=[
            RegexValidator(
                regex="[http]",
                message="Website URL must include https:// or http://",
                code="invalid_url",
            ),
        ],
        verbose_name="Link to your website",
    )
    relation_to_django = models.TextField(
        verbose_name="Your relation to Django",
    )
    email = models.EmailField(max_length=100)
    main_contact = models.CharField(
        max_length=100,
        verbose_name="The main point of contact",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.company_name

djangodenmark/apps/jobposts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Available titles for searching jobs
JOBTYPE_CHOICES = (
    ("PartTime", "Part-time"),
    ("FullTime", "Full-time"),
    ("Freelancer", "Freelancer"),
    ("Internship", "Internship"),
    ("Other", "Other"),
)


class Jobpost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job_title = models.CharField(max_length=60, verbose_name="Job title")
    job_company_name = models.CharField(max_length=100, verbose_name="Company name")
    job_description = models.TextField(verbose_name="Describe the position")
    job_type = models.CharField(
        max_length=11, choices=JOBTYPE_CHOICES, verbose_name="Job type"
    )
    job_location = models.CharField(max_length=100, verbose_name="Location")
    job_contact_person = models.CharField(max_length=80, verbose_name="Contact person")
    job_apply_url = models.URLField(
        max_length=200,
        blank=True,
        verbose_name="Link to job application",
    )

    def __str__(self):
        return f"{self.job_title} at {self.job_company_name}"

    def get_update_url(self):
        """return URL for update view - for use in templates
        since JS is being used on frontend, making this a model method is easier
        than using url template tag to avoid showing unnecessary errors in code editors
        """
        return reverse("jobpost_update", args=[self.pk])

djangodenmark/apps/companies/forms.py
from django.forms import ModelForm

from .models import Company


class CompanyForm(ModelForm):
    class Meta:
        model = Company
        exclude = ("user", "created_at")
        fields = "__all__"

company/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import CompanyForm
from .models import Company
from jobpost.models import Jobpost

# Create your views here.


# CreateView
class CompanyFormView(LoginRequiredMixin, CreateView):
    model = Company
    template_name = "company/createCompanyProfile.html"
    form_class = CompanyForm
    success_url = "/company/detailViewEditUpdateProfile"

    # Checks if data input is valid and saves object
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class CompanyView(ListView):
    model = Company
    template_name = "company/companyoverview.html"


# DetailView
# CompanyDetailViewEditUpdate takes 2 parameters LoginRequiredMixin to secure different
# functionalities for users when signed in or not and ListView.
class CompanyDetailView(DetailView):
    model = Company
    template_name = "company/detailViewCompanyProfile.html"
    fields = "__all__"


class CompanyDetailViewEditUpdate(LoginRequiredMixin, ListView):
    model = Company
    template_name = "company/detailViewEditUpdateProfile.html"
    fields = "__all__"

    # get_queryset(self) secures to display Company profiles that the User is creater/owner of.
    def get_queryset(self):
        return (
            super(CompanyDetailViewEditUpdate, self)
            .get_queryset()
            .filter(user=self.request.user)
        )

    # get_context_data(self, **kwargs) makes it possible for two ListViews containing different
    # sets of data to be displayed on the same html page. In this case objects from jobpost.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        my_jobposts = Jobpost.objects.filter(user=self.request.user)
        context["jobpost_list"] = my_jobposts
        return context


# UpdateView
class UpdateCompanyFormView(LoginRequiredMixin, UpdateView):
    model = Company
    template_name = "company/updateCompanyProfile.html"
    form_class = CompanyForm
    success_url = "/company/detailViewEditUpdateProfile"


# DeleteView
class DeleteCompanyFormView(DeleteView):
    model = Company
    template_name = "company/detailViewEditUpdateProfile.html"
    success_url = "/company/detailViewEditUpdateProfile"

djangodenmark/apps/companies/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import CompanyForm
from .models import Company
from djangodenmark.apps.jobposts.models import Jobpost


# CreateView
class CompanyFormView(LoginRequiredMixin, CreateView):
    model = Company
    template_name = "companies/createCompanyProfile.html"
    form_class = CompanyForm
    success_url = "/companies/detailViewEditUpdateProfile"

    # Checks if data input is valid and saves object
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class CompanyView(ListView):
    model = Company
    template_name = "companies/companyoverview.html"


# DetailView
# CompanyDetailViewEditUpdate takes 2 parameters LoginRequiredMixin to secure different
# functionalities for users when signed in or not and ListView.
class CompanyDetailView(DetailView):
    model = Company
    template_name = "companies/detailViewCompanyProfile.html"
    fields = "__all__"


class CompanyDetailViewEditUpdate(LoginRequiredMixin, ListView):
    model = Company
    template_name = "companies/detailViewEditUpdateProfile.html"
    fields = "__all__"

    # get_queryset(self) secures to display Company profiles that the User is creater/owner of.
    def get_queryset(self):
        return (
            super(CompanyDetailViewEditUpdate, self)
            .get_queryset()
            .filter(user=self.request.user)
        )

    # get_context_data(self, **kwargs) makes it possible for two ListViews containing different
    # sets of data to be displayed on the same html page. In this case objects from jobposts.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        my_jobposts = Jobpost.objects.filter(user=self.request.user)
        context["jobpost_list"] = my_jobposts
        return context


# UpdateView
class UpdateCompanyFormView(LoginRequiredMixin, UpdateView):
    model = Company
    template_name = "companies/updateCompanyProfile.html"
    form_class = CompanyForm
    success_url = "/companies/detailViewEditUpdateProfile"


# DeleteView
class DeleteCompanyFormView(DeleteView):
    model = Company
    template_name = "companies/detailViewEditUpdateProfile.html"
    success_url = "/companies/detailViewEditUpdateProfile"

djangodenmark/apps/companies/templates/companies/base.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

djangodenmark/apps/companies/templates/companies/companyoverview.html
{% extends "company/base.html" %}
{% block content %}
    <div class="company-overview row">
        <div class="col-12">
            <div class="text-center">
                <h1>Companies that use Django</h1>
                <p>Welcome to the overview for all the companies, that uses Django.</p>
            </div>
            <div class="card-container">
                {% for Company in company_list %}
                {% comment %} Each company is shown in the form of a bootstrap card {% endcomment %}
                <div class="card company-card">
                        <img class="company-logo" src="{{ Company.logo_image.url}}" alt="{{ Company.company_name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ Company.company_name }}</h5>
                            <p class="card-text company-description">{{ Company.description }}</p>
                            <button type="button" class="btn btn-django" data-bs-toggle="modal" data-bs-target="#exampleModal{{ Company.pk }}">See company profile</button>
                            <!-- Modal starts -->
                            <div class="modal fade" id="exampleModal{{ Company.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <img class="card-img-top company-logo" src="{{ Company.logo_image.url}}" alt="{{ Company.company_name }}">
                                    <h4 class="modal-title" id="exampleModalLabel">{{ Company.company_name }}</h4 >
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <br>
                                <div class="modal-body row">
                                    <div class="col-4">
                                        <h6>Company Info</h6>
                                        <div>{{ Company.email }}</div>
                                        <div class="company-url" onclick="window.location.href='{{ Company.website_url }}'">{{ Company.website_url }}</div>
                                    </div>
                                    <div class="col-8">
                                        <h5>Description:</h5>
                                        <p>{{ Company.description|linebreaks }}</p>
                                        <h5>Relation to Django:</h5>
                                        <p>{{ Company.relation_to_django|linebreaks }}</p>
                                    </div>
                                </div>
                                </div>
                            </div>
                            </div>
                            <!-- Modal ends -->
                        </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

djangodenmark/apps/companies/templates/companies/createCompanyProfile.html
{% extends "companies/base.html" %}
{% block content %}
<form method="post" novalidate enctype="multipart/form-data" class="create-form">
  <h1>Create your company profile</h1>
  {% comment %} base-form found in djangodenmark/templates {% endcomment %}
  {% include 'base-form.html' with form=form %}
  <button type="submit" class="btn btn-django">Create profile</button>
</form>
{% endblock %}

djangodenmark/apps/companies/templates/companies/detailViewEditUpdateProfile.html
{% extends "companies/companyoverview.html" %}

{% block content %}
{% comment %} COMPANIES on my page {% endcomment %}
    <div class="company-overview row">
        <div class="col-12">
            <div class="row">
                <h1 class="col-9">Your company profiles</h1>
                {% if user.is_authenticated %}
                    <!-- <button onclick="window.location.href='/company/createCompanyProfile/'" class="btn btn-django col-3">Create company Profile</button> -->
                    <div class="col-3 d-flex justify-content-end align-items-center">
                        <a href="{% url 'createCompanyProfile' %}" class="btn btn-django">Create Company Profile</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <br>
        <div class="col-12">
            <div class="card-container">
                {% for Company in company_list %}
                {% comment %} Each company is shown in the form of a bootstrap card {% endcomment %}
                <div class="card company-card">
                    <img class="card-img-top company-logo" src="{{ Company.logo_image.url}}" alt="{{ Company.company_name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ Company.company_name }}</h5>
                        <p class="card-text company-description">{{ Company.description }}</p>
                        <button type="button" class="btn btn-django" data-bs-toggle="modal" data-bs-target="#seeCompanyModal{{ Company.pk }}">See company profile</button>
                        <div class="btn-grouped">
                            <button class="btn btn-django" onclick="window.location.href='/company/{{ Company.pk }}/updateCompanyProfile'">Update</button>
                            <button type="button" class="btn btn-django" data-bs-toggle="modal" data-bs-target="#myPageModal{{ Company.pk }}">Delete</button>
                            {% comment %} delete company modal starts {% endcomment %}
                            <div class="modal" id="myPageModal{{ Company.pk }}" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{% url 'delete_company' pk=Company.pk %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
                                            <p>Are you sure you want to delete "{{ Company.company_name }}"?</p>
                                            <input class="btn btn-danger" type="submit" value="Delete Profile">
                                        </form>
                                    </div>
                                </div>
                            </div>
                            </div>
                            {% comment %} delete company modal ends {% endcomment %}
                        </div>
                        <!-- see company modal starts -->
                        <div class="modal fade" id="seeCompanyModal{{ Company.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <img class="card-img-top company-logo" src="{{ Company.logo_image.url}}" alt="{{ Company.company_name }}">
                                        <h4 class="modal-title" id="exampleModalLabel">{{ Company.company_name }}</h4 >
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <br>
                                    <div class="modal-body row">
                                        <div class="col-4">
                                            <h6>Company Info</h6>
                                            <div>{{ Company.email }}</div>
                                            <div class="company-url" onclick="window.location.href='{{ Company.website_url }}'">{{ Company.website_url }}</div>
                                        </div>
                                        <div class="col-8">
                                            <h5>Description:</h5>

                                            <p>{{ Company.description|linebreaks }}</p>
                                            <h5>Relation to Django:</h5>
                                            <p>{{ Company.relation_to_django|linebreaks }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% comment %} see company modal ends {% endcomment %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    {% comment %} JOB POSTS {% endcomment %}
    <div class="company-overview row">
        <div class="col-12">
            <div class="row">
                <h1 class="col-9">Your job posts</h1>
                {% if user.is_authenticated %}
                    <div class="col-3 d-flex justify-content-end align-items-center">
                        <a href="{% url 'jobpost_create' %}" class="btn btn-django">Create job post</a>
                    </div>
                {% endif %}
            </div>
        </div>
        <br>
        <div class="col-12">
            <div class="card-container">
                {% for Jobpost in jobpost_list %}
                {% comment %} Each job is shown in the form of a bootstrap card {% endcomment %}
                <div class="card company-card">
                    <div class="card-body">
                        <h5 class="card-title">{{ Jobpost.job_title }}</h5>
                        <p class="card-text company-description">{{ Jobpost.job_description }}</p>
                        <button type="button" class="btn btn-django" data-bs-toggle="modal" data-bs-target="#exampleModal{{ Jobpost.pk }}">See job post</button>
                        <div class="btn-grouped">
                            <button class="btn btn-django" onclick="window.location.href='{{ Jobpost.get_update_url }}'">Update</button>
                            {% comment %} delete job modal {% endcomment %}
                            <button type="button" class="btn btn-django" data-bs-toggle="modal" data-bs-target="#deleteJobModal{{ Jobpost.pk }}">Delete</button>
                            <div class="modal" id="deleteJobModal{{ Jobpost.pk }}" tabindex="-1" role="dialog">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="{% url 'jobpost_delete' pk=Jobpost.pk %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                                            <p>Are you sure you want to delete "{{ Jobpost.job_title }}"?</p>
                                            <input class="btn btn-danger" type="submit" value="Delete Job Post">
                                        </form>
                                    </div>
                                </div>
                            </div>
                            </div>
                            {% comment %} delete job modal ends {% endcomment %}
                        </div>
                        <!-- SEE JOB Modal starts -->
                        <div class="modal fade" id="exampleModal{{ Jobpost.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title" id="exampleModalLabel">{{ Jobpost.job_title }}</h4>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <br>
                                <div class="modal-body row">
                                    <div class="col-6">
                                        <h6>Job Info</h6>
                                        <div>{{ Jobpost.jobcompany_name }}</div>
                                        <div>{{ Jobpost.job_contact_person }}</div>
                                        <div>{{ Jobpost.job_location }}</div>
                                        <div>{{ Jobpost.job_type }}</div>
                                    </div>
                                    <div class="col-6">
                                        <h5>Description:</h5>
                                        <p>{{ Jobpost.job_description|linebreaks }}</p>
                                        <a href="{{ Jobpost.job_apply_url }}" target="_blank" class="btn btn-django">Apply here</a>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                        {% comment %} see job modal ends {% endcomment %}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

djangodenmark/apps/companies/templates/companies/updateCompanyProfile.html
{% extends "companies/base.html" %}
{% block content %}
{% load widget_tweaks %}

<form method="post" novalidate enctype="multipart/form-data" class="create-form">
  <h1>Update your company profile</h1>
  {% comment %} base-form found in djangodenmark/templates {% endcomment %}
  {% include 'base-form.html' with form=form %}
  <button type="submit" class="btn btn-django">Update profile</button>
</form>
{% endblock %}